### ISSUE TITLE
google_osconfig CPU usage continually increases

### ISSUE THREAD

**Issue by shaneqld** [GoogleCloudPlatform/osconfig#261] opened 2020-11-21 00:19 UTC
I have two VMs with the configuration below, and the CPU usage of process `google_osconfig` slowly and linearly increases over time.

On one VM, over a 30 day period, CPU usage increased from 11% to 58%.

On another VM, it increased from 0% on boot to 6% over 2 days, after which I updated `google-osconfig-agent`.  The CPU dropped back down to 0% and has increased to 9% over 3 days.

The CPU usage data I have referred to is from Monitoring within Compute Engine.  I can confirm using `top` that `google_osconfig` is using the majority of CPU.  If I restart `google-osconfig-agent`, CPU drops back down.

`journalctl`/`systemctl status` reports no logs for `google-osconfig-agent`.

Unlike #228, these VMs have connectivity to Google APIs.  They are also not generating large amounts of network traffic.

I have found [others with this issue](https://stackoverflow.com/questions/64345022/google-osconfigs-cpu-usage-of-vm-on-google-cloud-platform-increases-steadily) but have found no solutions.

Please let me know if I can provide any further information.

Configuration:

Image: `debian-10-buster-v20200910`
Machine type: e2-micro (2 vCPUs, 1 GB memory)

_Edit: rebased CPU usage percentages by -11% (was base load)_

**Comment by adjackura** [comment] 2020-11-23 17:57
What version of the agent are you currently running? v20200910 image should have a very recent version, but I just want to double check.

**Comment by adjackura** [comment] 2020-11-23 18:30
I do will build a test binary and run with extreme load to profile CPU usage.

Can I get the output of these commands?
top -p <osconfig pid> -b -n 1
ps -C google_osconfig -o %cpu,%mem

**Comment by shaneqld** [comment] 2020-11-23 23:29
Thanks for your reply.  Please see below requested information:

```
$ apt-cache policy google-osconfig-agent

google-osconfig-agent:
  Installed: 1:20200901.01-g1
```

```
$ top -p393 -b -n 1

top - 23:25:33 up 41 days, 21:35,  1 user,  load average: 0.02, 0.05, 0.01
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  3.2 sy,  0.0 ni, 96.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :    987.5 total,    197.4 free,    158.0 used,    632.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.    650.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  393 root      20   0  119244  24384  12188 S   6.7   2.4   1943:53 google_osconfig
```

```
$ ps -C google_osconfig -o %cpu,%mem

%CPU %MEM
 3.2  2.4
```

**Comment by adjackura** [comment] 2020-12-07 19:10
I am not able to reproduce this with the latest agent. I don't recall any specific changes that would have impacted CPU usage though, it's possible that there is something unique about your environment that is triggering this. I am still going to dig deeper into CPU perf on Linux to make sure there are no spinning goroutines (I have already done this on Windows, and on both Linux and Windows for memory).

I would suggest updating to the latest agent and see if you still have an issue, if you still do then I would expect my testing to reveal something, it just might be harder for me if my instance isn't exhibiting the same issue.

**Comment by adjackura** [comment] 2020-12-14 20:19
I think I found where the issue could be, I'll be getting an updated agent out this week. I still have no idea why you (and some others) are seeing such drastic increases in such a short time though as in my multi week testing I only saw a very minor increase.

**Comment by adjackura** [comment] 2020-12-15 19:04
Update to version 20201214.00, this hopefully will fix this issue for you.

**Comment by adjackura** [comment] 2020-12-29 17:39
I'm going to go ahead and close this as I'm pretty sure this has been fixed. Please reopen id the new version is still causing issues for you.

**Closed by adjackura** 2020-12-29 17:39 UTC

**Comment by Ark-kun** [comment] 2021-08-01 22:33
> Update to version 20201214.00, this hopefully will fix this issue for you.

What was the fix PR/commit?
